CREATE TABLE IF NOT EXISTS USERDATA (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(64) NOT NULL,
    firstName varchar(64 ) NOT NULL,
    lastName varchar(64) NOT NULL,
    email varchar(256) NOT NULL,
    birthdate varchar(64) NOT NULL,
    );

CREATE TABLE IF NOT EXISTS USERS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(64) NOT NULL,
    password varchar(256) NOT NULL,
    enabled INT NOT NULL
    );

CREATE TABLE IF NOT EXISTS AUTHORITIES (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(64) NOT NULL,
    authority varchar(64) NOT NULL
    );